# Generated by Django 2.2.16 on 2022-08-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220816_1805'),
        ('reviews', '0003_remove_comment_created'),
    ]

    operations = [
    ]
